Repository lion-packages/database, pull requests merged in 2025-04, with the labels that each got.

#53 Integrate Dependency-Review
  .github/workflows/php.yml
Labels: continuous integration

#56 Update README
  .github/README.md
Labels: documentation

#57 Added support for the GetQueryString interface
  src/LionDatabase/Connection.php
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Drivers/SQLite.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Interface/GetQueryStringInterface.php
  src/LionDatabase/Traits/GetQueryStringInterfaceTrait.php
  tests/ConnectionTest.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
  tests/Drivers/SQLiteTest.php
  tests/Drivers/Schema/MySQLTest.php
  tests/Provider/ConnectionProviderTrait.php
  tests/Provider/MySQLProviderTrait.php
  tests/Provider/MySQLSchemaProviderTrait.php
  tests/Provider/PostgreSQLProviderTrait.php
  tests/Provider/SQLiteProviderTrait.php
Labels: refactor, tests

#58 StringFactory is integrated
  src/LionDatabase/Connection.php
  src/LionDatabase/Helpers/FunctionsTrait.php
  src/LionDatabase/Helpers/KeywordsTrait.php
  src/LionDatabase/Helpers/StringFactory.php
  tests/Helpers/FunctionsTraitTest.php
  tests/Helpers/KeywordsTraitTest.php
  tests/Helpers/StringFactoryTest.php
  tests/Provider/FunctionsTraitProviderTrait.php
  tests/Provider/KeywordsTraitProviderTrait.php
  tests/Provider/StringFactoryProviderTrait.php
Labels: refactor, tests

#60 Modify parameter of the view function
  src/LionDatabase/Drivers/MySQL.php
  tests/Provider/MySQLProviderTrait.php
Labels: enhancement, tests

#61 Added support for DatabaseInterface
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Interface/Drivers/DatabaseInterface.php
  src/LionDatabase/Traits/Drivers/DatabaseInterfaceTrait.php
  tests/DriverTest.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
Labels: enhancement, refactor, tests

#62 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#65 Apply fixes from StyleCI
  src/LionDatabase/Connection.php
  tests/ConnectionTest.php
  tests/Provider/PostgreSQLProviderTrait.php
  tests/Provider/SQLiteProviderTrait.php
Labels: standardization

#64 Added StyleCI configuration
  .styleci.yml
  tests/ConnectionTest.php
  tests/Provider/PostgreSQLProviderTrait.php
  tests/Provider/SQLiteProviderTrait.php
Labels: continuous integration

#66 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#67 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#68 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration
