Repository lion-packages/database, pull requests merged in 2025-03, with the labels that each got.

#46 Added support for generating PDO connections without a defined database
  src/LionDatabase/Connection.php
  tests/ConnectionTest.php
  tests/Provider/ConnectionProviderTrait.php
Labels: enhancement, tests

#47 Fixed connection cache for server connections
  src/LionDatabase/Connection.php
  tests/ConnectionTest.php
  tests/Provider/ConnectionProviderTrait.php
Labels: bug

#49 Fixed variable initialization in database processes
  src/LionDatabase/Connection.php
  src/LionDatabase/Helpers/DriverTrait.php
Labels: bug

#50 Added support for clearing the database connection cache
  src/LionDatabase/Connection.php
  tests/ConnectionTest.php
Labels: enhancement

#51 Added a process method to run database processes
  src/LionDatabase/Connection.php
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Drivers/SQLite.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Helpers/DriverTrait.php
  src/LionDatabase/Interface/ConnectionConfigInterface.php
  src/LionDatabase/Interface/DatabaseConfigInterface.php
  src/LionDatabase/Interface/Drivers/UpdateInterface.php
  src/LionDatabase/Interface/QueryInterface.php
  src/LionDatabase/Interface/TransactionInterface.php
  src/LionDatabase/Traits/ConnectionInterfaceTrait.php
  src/LionDatabase/Traits/ExecuteInterfaceTrait.php
  src/LionDatabase/Traits/GetAllInterfaceTrait.php
  src/LionDatabase/Traits/GetInterfaceTrait.php
  src/LionDatabase/Traits/QueryInterfaceTrait.php
  src/LionDatabase/Traits/RunInterfaceTrait.php
  src/LionDatabase/Traits/TransactionInterfaceTrait.php
  tests/ConnectionTest.php
Labels: enhancement

#52 Add cache in workflow
  .github/workflows/php.yml
  Dockerfile
Labels: continuous integration
