Repository lion-packages/database, pull requests merged in 2025-01, with the labels that each got.

#27 Github Actions Integration
  .env.actions
  .env.example
  .github/workflows/php.yml
  .gitignore
  composer.json
  composer.lock
  docker-compose.yml
  phpunit.xml
  src/LionDatabase/Connection.php
  src/LionDatabase/Driver.php
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Helpers/Constants/MySQLConstants.php
  src/LionDatabase/Helpers/DriverTrait.php
  src/LionDatabase/Helpers/FunctionsTrait.php
  src/LionDatabase/Helpers/Interfaces/RunInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/TransactionInterfaceTrait.php
  src/LionDatabase/Helpers/KeywordsTrait.php
  src/LionDatabase/Interface/DatabaseEngine/MySQLInterface.php
  src/LionDatabase/Interface/DatabaseEngine/PostgreSQLInterface.php
  src/LionDatabase/Interface/QueryInterface.php
  tests/ConnectionTest.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
  tests/Drivers/Schema/MySQLTest.php
  tests/Helpers/FunctionsTraitTest.php
  tests/Provider/FunctionsTraitProviderTrait.php
  tests/Provider/MySQLSchemaProviderTrait.php
  tests/bootstrap.php
  tests/build/coverage/.gitignore
  tests/build/logs/.gitignore
Labels: documentation, continuous integration, dependencies

#28 Refactoring the use of the MySQL having statement
  src/LionDatabase/Drivers/MySQL.php
  test-report.sh
  test.sh
  tests/Drivers/MySQLTest.php
  tests/Provider/MySQLProviderTrait.php
Labels: refactor

#29 Update LICENSE
  LICENSE
Labels: documentation
