Repository lion-packages/database, pull requests merged in 2025-02, with the labels that each got.

#30 Documentation files have been relocated
  .github/CHANGELOG.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/README.md
  composer.lock
Labels: documentation

#31 Updated Github Actions settings
  .github/workflows/php.yml
Labels: continuous integration

#32 Standardization with PHP_CodeSniffer and PHPStan
  .github/workflows/php.yml
  Dockerfile
  phpstan.neon
  src/LionDatabase/Connection.php
  src/LionDatabase/Driver.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Helpers/Constants/MySQLConstants.php
  src/LionDatabase/Helpers/DriverTrait.php
  src/LionDatabase/Helpers/FunctionsTrait.php
  src/LionDatabase/Helpers/Interfaces/ConnectionInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/ExecuteInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/GetAllInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/GetInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/QueryInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/RunInterfaceTrait.php
  src/LionDatabase/Helpers/Interfaces/TransactionInterfaceTrait.php
  src/LionDatabase/Interface/ConnectionConfigInterface.php
  src/LionDatabase/Interface/DatabaseConfigInterface.php
  src/LionDatabase/Interface/DatabaseEngine/MySQLInterface.php
  src/LionDatabase/Interface/DatabaseEngine/PostgreSQLInterface.php
  src/LionDatabase/Interface/DatabaseEngineInterface.php
  src/LionDatabase/Interface/QueryInterface.php
  tests/ConnectionTest.php
  tests/DriverTest.php
  tests/Helpers/Constants/MySQLConstantsTest.php
  tests/Helpers/DriverTraitTest.php
  tests/Helpers/FunctionsTraitTest.php
  tests/Helpers/KeywordsTraitTest.php
  tests/Provider/ConnectionProviderTrait.php
  tests/Provider/CustomClassProvider.php
  tests/Provider/DriverTraitProviderTrait.php
  tests/Provider/FunctionsTraitProviderTrait.php
  tests/Provider/KeywordsTraitProviderTrait.php
  tests/Provider/MySQLProviderTrait.php
  tests/Provider/MySQLSchemaProviderTrait.php
  tests/Provider/PostgreSQLProviderTrait.php
  tests/bootstrap.php
Labels: continuous integration, standardization

#33 docs: the Code_of_Conduct is modified
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#34 Interfaces and traits are integrated into the logic of functions as abstract
  phpstan.neon
  phpunit.xml
  src/LionDatabase/Connection.php
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Interface/Drivers/AndInterface.php
  src/LionDatabase/Interface/Drivers/DeleteInterface.php
  src/LionDatabase/Interface/Drivers/InsertInterface.php
  src/LionDatabase/Interface/Drivers/OrInterface.php
  src/LionDatabase/Interface/Drivers/SelectInterface.php
  src/LionDatabase/Interface/Drivers/TableInterface.php
  src/LionDatabase/Interface/Drivers/UpdateInterface.php
  src/LionDatabase/Interface/Drivers/WhereInterface.php
  src/LionDatabase/Traits/ConnectionInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/AndInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/DeleteInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/InsertInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/OrInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/SelectInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/TableInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/UpdateInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/WhereInterfaceTrait.php
  src/LionDatabase/Traits/ExecuteInterfaceTrait.php
  src/LionDatabase/Traits/GetAllInterfaceTrait.php
  src/LionDatabase/Traits/GetInterfaceTrait.php
  src/LionDatabase/Traits/QueryInterfaceTrait.php
  src/LionDatabase/Traits/RunInterfaceTrait.php
  src/LionDatabase/Traits/TransactionInterfaceTrait.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
  tests/Provider/PostgreSQLProviderTrait.php
Labels: enhancement, tests

#35 Interfaces and traits are integrated into the logic of functions as abstract
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Helpers/DriverTrait.php
  src/LionDatabase/Interface/Drivers/BulkInterface.php
  src/LionDatabase/Interface/Drivers/EqualToInterface.php
  src/LionDatabase/Interface/Drivers/GreaterThanInterface.php
  src/LionDatabase/Interface/Drivers/GreaterThanOrEqualToInterface.php
  src/LionDatabase/Interface/Drivers/LessThanInterface.php
  src/LionDatabase/Interface/Drivers/LessThanOrEqualToInterface.php
  src/LionDatabase/Interface/Drivers/NotEqualToInterface.php
  src/LionDatabase/Interface/SchemaDriverInterface.php
  src/LionDatabase/Traits/ConnectionInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/BulkInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/EqualToInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/GreaterThanInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/GreaterThanOrEqualToInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/LessThanInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/LessThanOrEqualToInterfaceTrait.php
  src/LionDatabase/Traits/Drivers/NotEqualToInterfaceTrait.php
  src/LionDatabase/Traits/ExecuteInterfaceTrait.php
  src/LionDatabase/Traits/GetAllInterfaceTrait.php
  src/LionDatabase/Traits/GetInterfaceTrait.php
  src/LionDatabase/Traits/QueryInterfaceTrait.php
  src/LionDatabase/Traits/RunInterfaceTrait.php
  src/LionDatabase/Traits/SchemaDriverInterfaceTrait.php
  src/LionDatabase/Traits/TransactionInterfaceTrait.php
  tests/Drivers/PostgreSQLTest.php
  tests/Provider/PostgreSQLProviderTrait.php
Labels: enhancement, tests

#36 Process execution is corrected
  src/LionDatabase/Connection.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Interface/ReadDatabaseDataInterface.php
  src/LionDatabase/Traits/ConnectionInterfaceTrait.php
  src/LionDatabase/Traits/ExecuteInterfaceTrait.php
  src/LionDatabase/Traits/GetAllInterfaceTrait.php
  src/LionDatabase/Traits/GetInterfaceTrait.php
  src/LionDatabase/Traits/RunInterfaceTrait.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
  tests/Drivers/Schema/MySQLTest.php
Labels: bug

#37 Fixed data type for function return
  src/LionDatabase/Interface/ReadDatabaseDataInterface.php
  src/LionDatabase/Traits/GetAllInterfaceTrait.php
Labels: bug

#38 ON UPDATE support added to MySQL Schema
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Interface/Drivers/OnUpdateInterface.php
  src/LionDatabase/Traits/Drivers/OnUpdateInterfaceTrait.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
  tests/Drivers/Schema/MySQLTest.php
Labels: enhancement

#39 Support for multiple default values ​​is added in MySQL Schema
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Helpers/DriverTrait.php
  tests/Drivers/Schema/MySQLTest.php
  tests/Provider/DriverTraitProviderTrait.php
  tests/Provider/MySQLSchemaProviderTrait.php
Labels: enhancement, tests

#40 Fixed condition to add default values ​​in MySQL Schema
  src/LionDatabase/Drivers/Schema/MySQL.php
  tests/Drivers/Schema/MySQLTest.php
Labels: bug

#41 Added reserved words for default values
  src/LionDatabase/Helpers/DriverTrait.php
  tests/Provider/DriverTraitProviderTrait.php
Labels: bug

#42 Integrating the rowCount function
  docker-compose.yml
  src/LionDatabase/Connection.php
  src/LionDatabase/Driver.php
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Helpers/DriverTrait.php
  src/LionDatabase/Interface/ConnectionConfigInterface.php
  src/LionDatabase/Interface/DatabaseConfigInterface.php
  src/LionDatabase/Interface/RowCountInterface.php
  src/LionDatabase/Interface/RunDatabaseProcessesInterface.php
  src/LionDatabase/Traits/ExecuteInterfaceTrait.php
  src/LionDatabase/Traits/RowCountInterfaceTrait.php
  tests/DriverTest.php
  tests/Drivers/MySQLTest.php
  tests/Drivers/PostgreSQLTest.php
  tests/Drivers/Schema/MySQLTest.php
Labels: enhancement, continuous integration, tests

#43 RunDatabaseProcessesInterface is renamed to ExecuteInterface
  src/LionDatabase/Drivers/MySQL.php
  src/LionDatabase/Drivers/PostgreSQL.php
  src/LionDatabase/Drivers/Schema/MySQL.php
  src/LionDatabase/Interface/ExecuteInterface.php
  tests/Drivers/Schema/MySQLTest.php
  tests/Provider/CustomClassProvider.php
Labels: refactor

#44 Static support added for DatabaseCapsuleInterface
  src/LionDatabase/Interface/DatabaseCapsuleInterface.php
  tests/Provider/PostgreSQLProviderTrait.php
Labels: enhancement
